#ifndef VGA_COLOR_H
#define VGA_COLOR_H

#define BG_BLACK_FG_BLACK                                   0X00
#define BG_BLACK_FG_BLUE                                    0X01
#define BG_BLACK_FG_GREEN                                   0X02
#define BG_BLACK_FG_CYAN                                    0X03
#define BG_BLACK_FG_MEHARON                                 0X04
#define BG_BLACK_FG_PINK                                    0X05
#define BG_BLACK_FG_BROWN                                   0X06
#define BG_BLACK_FG_GREY                                    0X07
#define BG_BLACK_FG_DARKGREY                                0X08
#define BG_BLACK_FG_LIGHTBLUE                               0X09
#define BG_BLACK_FG_BRIGHTGREEN                             0X0A
#define BG_BLACK_FG_BRIGHTCYAN                              0X0B
#define BG_BLACK_FG_BRIGHTRED                               0X0C
#define BG_BLACK_FG_BRIGHTPINK                              0X0D
#define BG_BLACK_FG_BRIGHTYELLOW                            0X0E
#define BG_BLACK_FG_WHITE                                   0X0F

#define BG_BLACK_FG_BLACK                                   0X10
#define BG_BLUE_FG_BLACK                                    0X11
#define BG_GREEN_FG_LIGHTBLACK                              0X12
#define BG_CYAN_FG_DARKGREY                                 0X13
#define BG_MEHARON_FG_CHARCOLGREY                           0X14
#define BG_PINK_FG_DAVYGREY                                 0X15
#define BG_BROWN_FG_MIDGREY                                 0X16
#define BG_GREY_FG_SMOKEYGREY                               0X17
#define BG_DARKGREY_FG_NATURALGREY                          0X18
#define BG_LIGHTBLUE_FG_DUSTYGREY                           0X19
#define BG_BRIGHTGREEN_FG_HITGREY                           0X1A
#define BG_BRIGHTCYAN_FG_ASHGREY                            0X1B
#define BG_BRIGHTRED_FG_SILVERGREY                          0X1C
#define BG_BRIGHTPINK_FG_LIGHTGREY                          0X1D
#define BG_BRIGHTYELLOW_FG_LIGHTWHITE                       0X1E
#define BG_WHITE_FG_WHITE                                   0X1F

#define BG_BLACK_FG_BLUE                                    0X20
#define BG_BLUE_FG_VIBRANTBLUEPURPLE                        0X21
#define BG_GREEN_FG_VIBRANTPURPLE                           0X22
#define BG_CYAN_FG_VIBRANTPURPLEMAGENTA                     0X23
#define BG_MEHARON_FG_VIBRANTMAGENTA                        0X24
#define BG_PINK_FG_VIBRANTREDDISHMAGENTA                    0X25
#define BG_BROWN_FG_VIBRANTMAGENTARED                       0X26
#define BG_GREY_FG_VIBRANTPINKISHRED                        0X27
#define BG_DARKGREY_FG_VIBRANTRED                           0X28
#define BG_LIGHTBLUE_FG_VIBRANTREDORANGE                    0X29
#define BG_BRIGHTGREEN_FG_VIBRANTORANGE                     0X2A
#define BG_BRIGHTCYAN_FG_VIBRANTORANGEYELLO                 0X2B
#define BG_BRIGHTRED_FG_VIBRANTYELLOW                       0X2C    
#define BG_BRIGHTPINK_FG_VIBRANTGREENISHYELLOW              0X2D
#define BG_BRIGHTYELLOW_FG_VIBRANTYELLOWGREEN               0X2E
#define BG_WHITE_FG_VIBRANTYELLOWISHGREEN                   0X2F

#define BG_BLACK_FG_VIBRANTGREEN                            0X30
#define BG_BLUE_FG_VIBRANTTEALISHGREEN                      0X31
#define BG_GREEN_FG_VIBRANTGREENCYAN                        0X32
#define BG_CYAN_FG_VIBRANTGREENISHCYAN                      0X33
#define BG_MEHARON_FG_VIBRANTCYAN                           0X34
#define BG_PINK_FG_VIBRANTBLUISHCYAN                        0X35
#define BG_BROWN_FG_VIBRANTCYANBLUE                         0X36
#define BG_GREY_FG_VIBRANTTEALISHBLUE                       0X37
#define BG_DARKGREY_FG_PASTELBLUE                           0X38
#define BG_LIGHTBLUE_FG_PASTELBLUEPURPLE                    0X39
#define BG_BRIGHTGREEN_FG_PASTELPURPLE                      0X3A
#define BG_BRIGHTCYAN_FG_PASTELPURPLEMAGENTA                0X3B
#define BG_BRIGHTRED_FG_PASTELMAGENTA                       0X3C
#define BG_BRIGHTPINK_FG_PASTELREDDISHMAGENTA               0X3D
#define BG_BRIGHTYELLOW_FG_PASTELMAGENTARED                 0X3E
#define BG_WHITE_FG_PASTELPINKISHRED                        0X3F

#define BG_BLACK_FG_PASTELRED                               0X40
#define BG_BLUE_FG_PASTELREDORANGE                          0X41
#define BG_GREEN_FG_PASTELORANGE                            0X42
#define BG_CYAN_FG_PASTELORANGEYELLOW                       0X43
#define BG_MEHARON_FG_PASTELYELLOW                          0X44
#define BG_PINK_FG_PASTELGREENISHYELLOW                     0X45
#define BG_BROWN_FG_PATELYELLOWGREEN                        0X46
#define BG_GREY_FG_PASTELYELLOWISHGREEN                     0X47
#define BG_DARKGREY_FG_PATELGREEN                           0X48
#define BG_LIGHTBLUE_FG_PASTELTEALISHGREEN                  0X49
#define BG_BRIGHTGREEN_FG_PASTELGREENCYAN                   0X4A
#define BG_BRIGHTCYAN_FG_PASTELGREENISHCYAN                 0X4B
#define BG_BRIGHTRED_FG_PASTELCYAN                          0X4C
#define BG_BRIGHTPINK_FG_PASTELBLUISHCYAN                   0X4D
#define BG_BRIGHTYELLOW_FG_PASTELCYANBLUE                   0X4E
#define BG_WHITE_FG_PASTELTEALISHBLUE                       0X4F

#define BG_BLACK_FG_PASTELBLUE                              0X50
#define BG_BLUE_FG_PASTELBLUEPURPLE                         0X51
#define BG_GREEN_FG_PASTELPURPLE                            0X52
#define BG_CYAN_FG_PASTELPURPLEMAGENTA                      0X53
#define BG_MEHARON_FG_PASTELMAGENTA                         0X54
#define BG_PINK_FG_PASTELREDDISHMAGENTA                     0X55
#define BG_BROWN_FG_PASTELMAGENTARED                        0X56
#define BG_GREY_FG_PASTELPINKISHRED                         0X57
#define BG_DARKGREY_FG_PASTELRED                            0X58
#define BG_LIGHTBLUE_FG_PASTELREDORANGE                     0X59
#define BG_BRIGHTGREEN_FG_PASTELORANGE                      0X5A
#define BG_BRIGHTCYAN_FG_PASTELORANGEYELLOW                 0X5B
#define BG_BRIGHTRED_FG_PASTELYELLOW                        0X5C
#define BG_BRIGHTPINK_FG_PASTELGREENISHYELLOW               0X5D
#define BG_BRIGHTYELLOW_FG_PASTELYELLOWGREEN                0X5E
#define BG_WHITE_FG_PASTELYELLOWISHGREEN                    0X5F

#define BG_BLACK_FG_PASTELGREEN                              0X60
#define BG_BLUE_FG_PASTELTEALISHGREEN                        0X61
#define BG_GREEN_FG_PASTELGREENCYAN                          0X62
#define BG_CYAN_FG_PASTELGREENISHCYAN                        0X63
#define BG_MEHARON_FG_PASTELCYAN                             0X64
#define BG_PINK_FG_PASTELBLUISHCYAN                          0X65
#define BG_BROWN_FG_PASTELCYANBLUE                           0X66
#define BG_GREY_FG_PASTELTEALISHBLUE                         0X67
#define BG_DARKGREY_FG_VIBRANTBLUE                           0X68
#define BG_LIGHTBLUE_FG_VIBRANTBLUEPURPLE                    0X69
#define BG_BRIGHTGREEN_FG_VIBRANTPURPLE                      0X6A
#define BG_BRIGHTCYAN_FG_VIBRANTPURPLEMAGENTA                0X6B
#define BG_BRIGHTRED_FG_VIBRANTMAGENTA                       0X6C
#define BG_BRIGHTPINK_FG_VIBRANTREDDISHMAGENTA               0X6D
#define BG_BRIGHTYELLOW_FG_VIBRANTMAGENTARED                 0X6E
#define BG_WHITE_FG_VIBRANTPINKISHRED                        0X6F

#define BG_BLACK_FG_VIBRANTRED                               0X70
#define BG_BLUE_FG_VIBRANTREDORANGE                          0X71
#define BG_GREEN_FG_VIBRANTORANGE                            0X72
#define BG_CYAN_FG_VIBRANTORANGEYELLOW                       0X73
#define BG_MEHARON_FG_VIBRANTYELLOW                          0X74
#define BG_PINK_FG_VIBRANTGREENISHYELLOW                     0X75
#define BG_BROWN_FG_VIBRANTYELLOWGREEN                       0X76
#define BG_GREY_FG_VIBRANTYELLOWISHGREEN                     0X77
#define BG_DARKGREY_FG_VIBRANTGREEN                          0X78
#define BG_LIGHTBLUE_FG_VIBRANTTEALISHGREEN                  0X79
#define BG_BRIGHTGREEN_FG_VIBRANTGREENCYAN                   0X7A
#define BG_BRIGHTCYAN_FG_VIBRANTGREENISHCYAN                 0X7B
#define BG_BRIGHTRED_FG_VIBRANTCYAN                          0X7C
#define BG_BRIGHTPINK_FG_VIBRANTBLUISHCYAN                   0X7D
#define BG_BRIGHTYELLOW_FG_VIBRANTCYANBLUE                   0X7E
#define BG_WHITE_FG_VIBRANTTEALISHBLUE                       0X7F

#define BG_BLACK_FG_PASTELBLUE                               0X80
#define BG_BLUE_FG_PASTELBLUEPURPLE                          0X81
#define BG_GREEN_FG_PASTELPURPLE                             0X82
#define BG_CYAN_FG_PASTELPURPLEMAGENTA                       0X83
#define BG_MEHARON_FG_PASTELMAGENTA                          0X84
#define BG_PINK_FG_PASTELREDDISHMAGENTA                      0X85
#define BG_BROWN_FG_PASTELMAGENTARED                         0X86
#define BG_GREY_FG_PASTELPINKISHRED                          0X87
#define BG_DARKGREY_FG_PASTELRED                             0X88
#define BG_LIGHTBLUE_FG_PASTELREDORANGE                      0X89
#define BG_BRIGHTGREEN_FG_PASTELORANGE                       0X8A
#define BG_BRIGHTCYAN_FG_PASTELORANGEYELLOW                  0X8B
#define BG_BRIGHTRED_FG_PASTELYELLOW                         0X8C
#define BG_BRIGHTPINK_FG_PASTELGREENISHYELLOW                0X8D
#define BG_BRIGHTYELLOW_FG_PASTELYELLOWGREEN                 0X8E
#define BG_WHITE_FG_PASTELYELLOWISHGREEN                     0X8F

#define BG_BLACK_FG_PASTELGREEN                              0X90
#define BG_BLUE_FG_PASTELTEALISHGREEN                        0X91
#define BG_GREEN_FG_PASTELGREENCYAN                          0X92
#define BG_CYAN_FG_PASTELGREENISHCYAN                        0X93
#define BG_MEHARON_FG_PASTELCYAN                             0X94
#define BG_PINK_FG_PASTELBLUISHCYAN                          0X95
#define BG_BROWN_FG_PASTELCYANBLUE                           0X96
#define BG_GREY_FG_PASTELTEALISHBLUE                         0X97
#define BG_DARKGREY_FG_PASTELBLUE                            0X98
#define BG_LIGHTBLUE_FG_PASTELBLUEPURPLE                     0X99
#define BG_BRIGHTGREEN_FG_PASTELPURPLE                       0X9A
#define BG_BRIGHTCYAN_FG_PASTELPURPLEMAGENTA                 0X9B
#define BG_BRIGHTRED_FG_PASTELMAGENTA                        0X9C
#define BG_BRIGHTPINK_FG_PASTELREDDISHMAGENTA                0X9D
#define BG_BRIGHTYELLOW_FG_PASTELMAGENTARED                  0X9E
#define BG_WHITE_FG_PASTELPINKISHRED                         0X9F

#define BG_BLACK_FG_PASTELRED                                0XA0
#define BG_BLUE_FG_PASTELREDORANGE                           0XA1
#define BG_GREEN_FG_PASTELORANGE                             0XA2
#define BG_CYAN_FG_PASTELORANGEYELLOW                        0XA3
#define BG_MEHARON_FG_PASTELYELLOW                           0XA4
#define BG_PINK_FG_PASTELGREENISHYELLOW                      0XA5
#define BG_BROWN_FG_PASTELYELLOWGREEN                        0XA6
#define BG_GREY_FG_PASTELYELLOWISHGREEN                      0XA7
#define BG_DARKGREY_FG_PASTELGREEN                           0XA8
#define BG_LIGHTBLUE_FG_PASTELTEALISHGREEN                   0XA9
#define BG_BRIGHTGREEN_FG_PASTELGREENCYAN                    0XAA
#define BG_BRIGHTCYAN_FG_PASTELGREENISHCYAN                  0XAB
#define BG_BRIGHTRED_FG_PASTELCYAN                           0XAC
#define BG_BRIGHTPINK_FG_PASTELBLUISHCYAN                    0XAD
#define BG_BRIGHTYELLOW_FG_PASTELCYANBLUE                    0XAE
#define BG_WHITE_FG_PASTELTEALISHBLUE                        0XAF

#define BG_BLACK_FG_VIBRANTBLUE                              0XB0
#define BG_BLUE_FG_VIBRANTBLUEPURPLE                         0XB1
#define BG_GREEN_FG_VIBRANTPURPLE                            0XB2
#define BG_CYAN_FG_VIBRANTPURPLEMAGENTA                      0XB3
#define BG_MEHARON_FG_VIBRANTMAGENTA                         0XB4
#define BG_PINK_FG_VIBRANTREDDISHMAGENTA                     0XB5
#define BG_BROWN_FG_VIBRANTMAGENTARED                        0XB6
#define BG_GREY_FG_VIBRANTPINKISHRED                         0XB7
#define BG_DARKGREY_FG_VIBRANTRED                            0XB8
#define BG_LIGHTBLUE_FG_VIBRANTREDORANGE                     0XB9
#define BG_BRIGHTGREEN_FG_VIBRANTORANGE                      0XBA
#define BG_BRIGHTCYAN_FG_VIBRANTORANGEYELLOW                 0XBB
#define BG_BRIGHTRED_FG_VIBRANTYELLOW                        0XBC
#define BG_BRIGHTPINK_FG_VIBRANTGREENISHYELLOW               0XBD
#define BG_BRIGHTYELLOW_FG_VIBRANTYELLOWGREEN                0XBE
#define BG_WHITE_FG_VIBRANTYELLOWISHGREEN                    0XBF

#define BG_BLACK_FG_VIBRANTGREEN                             0XC0
#define BG_BLUE_FG_VIBRANTTEALISHGREEN                       0XC1
#define BG_GREEN_FG_VIBRANTGREENCYAN                         0XC2
#define BG_CYAN_FG_VIBRANTGREENISHCYAN                       0XC3
#define BG_MEHARON_FG_VIBRANTCYAN                            0XC4
#define BG_PINK_FG_VIBRANTBLUISHCYAN                         0XC5
#define BG_BROWN_FG_VIBRANTCYANBLUE                          0XC6
#define BG_GREY_FG_VIBRANTTEALISHBLUE                        0XC7
#define BG_DARKGREY_FG_MEDIUMBLUE                            0XC8
#define BG_LIGHTBLUE_FG_MEDIUMBLUEPURPLE                     0XC9
#define BG_BRIGHTGREEN_FG_MEDIUMPURPLE                       0XCA
#define BG_BRIGHTCYAN_FG_MEDIUMPRUPLEMAGENTA                 0XCB
#define BG_BRIGHTRED_FG_MEDIUMMAGENTA                        0XCC
#define BG_BRIGHTPINK_FG_MEDIUMREDDISHMAGENTA                0XCD
#define BG_BRIGHTYELLOW_FG_MEDIUMMAGENTARED                  0XCE
#define BG_WHITE_FG_MEDIUMPINKISHRED                         0XCF

#define BG_BLACK_FG_MEDIUMRED                                0XD0
#define BG_BLUE_FG_MEDIUMREDORANGE                           0XD1
#define BG_GREEN_FG_MEDIUMORANGE                             0XD2
#define BG_CYAN_FG_MEDIUMORANGEYELLOW                        0XD3
#define BG_MEHARON_FG_MEDIUMYELLOW                           0XD4
#define BG_PINK_FG_MEDIUMGREENISHYELLOW                      0XD5
#define BG_BROWN_FG_MEDIUMYELLOWGREEN                        0XD6
#define BG_GREY_FG_MEDIUMYELLOWISHGREEN                      0XD7
#define BG_DARKGREY_FG_MEDIUMGREEN                           0XD8
#define BG_LIGHTBLUE_FG_MEDIUMTEALISHGREEN                   0XD9
#define BG_BRIGHTGREEN_FG_MEDIUMGREENCYAN                    0XDA
#define BG_BRIGHTCYAN_FG_MEDIUMGREENISHCYAN                  0XDB
#define BG_BRIGHTRED_FG_MEDIUMCYAN                           0XDC
#define BG_BRIGHTPINK_FG_MEDIUMBLUISHCYAN                    0XDD
#define BG_BRIGHTYELLOW_FG_MEDIUMCYANBLUE                    0XDE
#define BG_WHITE_FG_MEDIUMTEALISHBLUE                        0XDF

#define BG_BLACK_FG_PASTELBLUE                               0XE0
#define BG_BLUE_FG_PASTELBLUEPURPLE                          0XE1
#define BG_GREEN_FG_PASTELBLUISHPURPLE                       0XE2
#define BG_CYAN_FG_PASTELPURPLYMAGENTA                       0XE3
#define BG_MEHARON_FG_PASTELMAGENTA                          0XE4
#define BG_PINK_FG_PASTELREDDISHMAGENTA                      0XE5
#define BG_BROWN_FG_PASTELPINKISHRED                         0XE6
#define BG_GREY_FG_PASTELPINKISHRED                          0XE7
#define BG_DARKGREY_FG_PASTELRED                             0XE8
#define BG_LIGHTBLUE_FG_PASTELREDORANGE                      0XE9
#define BG_BRIGHTGREEN_FG_PASTELREDDISHORANGE                0XEA
#define BG_BRIGHTCYAN_FG_PASTELORANGEYELLOW                  0XEB
#define BG_BRIGHTRED_FG_PASTELYELLOW                         0XEC
#define BG_BRIGHTPINK_FG_PASTELGREENISHYELLOW                0XED
#define BG_BRIGHTYELLOW_FG_PATELYELLOWISHGREEN               0XEE
#define BG_WHITE_FG_PASTELYELLOWISHGREEN                     0XEF

#define BG_BLACK_FG_PASTELGREEN                              0XF0
#define BG_BLUE_FG_PASTELTEALISHGREEN                        0XF1
#define BG_GREEN_FG_PASTELGREENCYAN                          0XF2
#define BG_CYAN_FG_PASTELGREENISHCYAN                        0XF3
#define BG_MEHARON_FG_PASTELCYAN                             0XF4
#define BG_PINK_FG_PASTELBLUISHCYAN                          0XF5
#define BG_BROWN_FG_PASTELTEALISHCYAN                        0XF6
#define BG_GREY_FG_PASTELTEALISHBLUE                         0XF7
#define BG_DARKGREY_FG_BLACK                                 0XF8
#define BG_LIGHTBLUE_FG_BLACK                                0XF9
#define BG_BRIGHTGREEN_FG_BLACK                              0XFA
#define BG_BRIGHTCYAN_FG_BLACK                               0XFB
#define BG_BRIGHTRED_FG_BLACK                                0XFC
#define BG_BRIGHTPINK_FG_BLACK                               0XFD
#define BG_BRIGHTYELLOW_FG_BLACK                             0XFE
#define BG_WHITE_FG_BLACK                                    0XFF

#endif /*VGA_COLOR_H*/
